---
- name: Deploy Monitoring Stack to AWS
  hosts: all           # سيقوم باستخدام الـ IP الموجود في ملف الـ inventory
  become: yes          # للتشغيل بصلاحيات sudo
  
  tasks:
    - name: Ensure the project directory exists
      file:
        path: /home/ubuntu/monitoring-project
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Run Docker Compose Up
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/monitoring-project
