name: Ansible Automation

on:
  push:
    branches:
      - master

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
