name: Ansible Grafana Deploy
on: [push]

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install ansible
          ansible-galaxy collection install community.grafana

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
        env:
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
